import type { RulesetConfig } from './types.ts';

export const THEATER_DEATH_13: RulesetConfig = {
  rulesetId: 'theater-death',
  version: '1.1',
  mode: 'formal',
  roles: {
    laike: 1,
    door: 1,
    water: 1,
    descender: 1,
    researcher: 1,
    civilian: 4,
    death: 1,
    spirit: 2,
    mourner: 1,
  },
  timersSeconds: {
    faction: 90,
    ability: 45,
    vote: 60,
    speech: 60,
    election: 30,
    handover: 45,
    lastWords: 60,
    tieSpeech: 45,
  },
  sheriff: {
    enabled: true,
    voteWeight: 1.5,
    handover: 'designate_or_destroy',
  },
  lastWords: {
    firstNight: true,
    dayEliminated: true,
    otherNights: false,
  },
  teamConfirm: 'unanimous_by_revision',
  duplicateTargetPolicy: 'allow',
  attackOrder: 'seat_asc_then_source_priority',
  researcherAnnouncement: {
    count: 'alive_at_announcement',
    includesMourner: true,
  },
  stageTriggerSnapshot: 'death_event',
  replayDisclosure: 'all_chat_and_action_log',
  stage1SpiritQuota: 'eligibleLivingSpiritCount',
  stage1DeathQuota: 2,
  stage1OverkillThreshold: 'initialSpiritCount',
  stage2JointQuota: 2,
  guardTargets: 2,
  guardBlocksPerTarget: 1,
  simultaneousWinPriority: 'death_faction',
  researcherCondition: 'currently_dead',
};
